[package]
name = "tomling"
description = "A simple TOML parser"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = { version = "0.6.20", default-features = false, features = [
    "alloc",
    "simd",
] }
