[package]
name = "tomling"
description = "A simple TOML parser"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde", "cargo-toml"]
cargo-toml = ["serde"]

[dependencies]
winnow = { version = "0.6.20", default-features = false, features = [
    "alloc",
    "simd",
] }
serde = { version = "1.0.215", default-features = false, optional = true, features = [
    "derive",
    "alloc",
] }
